name: Intersmash Tests - Simple build + unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  simple-build-and-unit-tests-wildfly:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Simple build and unit tests (WildFly)
        run: mvn clean install --batch-mode -DskipITs

  simple-build-and-unit-tests-jboss-eap:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Simple build and unit tests (JBoss EAP)
        run: mvn clean install --batch-mode -Pwildfly-target-distribution.jboss-eap -DskipITs

  simple-build-and-unit-tests-jboss-eap-xp:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Simple build and unit tests (JBoss EAP XP)
        run: mvn clean install --batch-mode -Pwildfly-target-distribution.jboss-eap-xp -DskipITs
